### PR TITLE
Handle failed API calls (fix #3)

### LINKED ISSUE #3: Handle failed API calls
Could have a toast popup to inform the user that it's failed.

### PR DESCRIPTION
**Pull request by mike100001**
@willbeaufoy the only thing I can find that doesn't work is the "Add Holding" fail. Pretty sure is that this is due to the way the props are passed in a different way and I haven't got the syntax for passing the notification function back quite right. Compiles ok though.

I've deliberately left out the set message and alert colour back to blank or undefined on the handle close function for the Snackbox. This is because the alert colour switches to green on close and if you reset the message string to ' ' it resizes the alert box and just looks a bit naff.

### CODE REVIEW

File: client/src/App.tsx [hunk 1]
```diff
@@ -6,6 +6,8 @@ import React, {useEffect, useState} from 'react';
 
 import {withAuthenticator} from '@aws-amplify/ui-react';
 import CircularProgress from '@material-ui/core/CircularProgress';
+import {Snackbar} from '@material-ui/core';
+import MuiAlert, {Color as AlertColor} from '@material-ui/lab/Alert';
```
Comment (willbeaufoy) [inline client/src/App.tsx]: Have you installed the Typescript import sorter plugin as specified here? https://github.com/willbeaufoy/portfolio-tracker#code-editor

I may not have mentioned it to you, apologies if not. Because it doesn't look like it's run here. Please install it and then re-save all the files you've changed so things are consistent.

File: client/src/App.tsx [hunk 2]
```diff
@@ -52,12 +71,22 @@ function App() {
...
+            <MuiAlert variant='filled' elevation={6} severity={alertColor}>
+              {snackbarMessage}
+            </MuiAlert>
+          </Snackbar>
         </div>
       </ConfirmProvider>
     );
   }
 }
-
```
Comment (willbeaufoy) [inline client/src/App.tsx]: Please put this blank line back.

File: client/src/holdings/AddDividendDialog.tsx [hunk 3]
```diff
@@ -61,7 +66,7 @@ export function AddDividendDialog({holding, onDividendCreated}: IProps) {
               onDividendCreated(dividend);
               setOpen(false);
             } catch (err) {
-              console.error(err);
+              showNotification(`Create Dividend ${holding.symbol} failed!`, 'error');
```
Comment (willbeaufoy) [inline client/src/holdings/AddDividendDialog.tsx]: Nit: Can it be

`Create dividend for ${holding.symbol} failed!`

Just reads a bit better to me

File: client/src/holdings/AddTradeDialog.tsx [hunk 4]
```diff
@@ -81,7 +82,7 @@ export function AddTradeDialog({holding, onTradeCreated}: AddTradeDialogProps) {
               onTradeCreated(trade);
               setOpen(false);
             } catch (err) {
-              console.error(err);
+              showNotification(`Create Trade ${holding.symbol} failed!`, 'error');
```
Comment (willbeaufoy) [inline client/src/holdings/AddTradeDialog.tsx]: Can this be 'Create trade for ${holding.symbol} failed!'

File: client/src/holdings/AddTradeDialog.tsx [hunk 5]
```diff
@@ -21,9 +21,10 @@ import {CreateTradeData, Holding, TradeCategory} from '../types';
 export type AddTradeDialogProps = {
   holding: Holding;
   onTradeCreated: Function;
+  showNotification: Function;
 };
 
-export function AddTradeDialog({holding, onTradeCreated}: AddTradeDialogProps) {
+export function AddTradeDialog({holding, onTradeCreated, showNotification,}: AddTradeDialogProps) {
```
Comment (willbeaufoy) [inline client/src/holdings/AddTradeDialog.tsx]: Remove comma from after showNotification

File: client/src/holdings/AddHoldingForm.tsx [hunk 6]
```diff
@@ -13,10 +13,14 @@ import {CURRENCIES} from '../constants';
...
   onHoldingCreated: Function;
+  showNotification: Function;
 };
 
 /** Form to add a holding. */
-export function AddHoldingForm(props: AddHoldingFormProps) {
+export function AddHoldingForm(
+  props: AddHoldingFormProps,
+  showNotification: Function
+) {
```
Comment (willbeaufoy) [inline client/src/holdings/AddHoldingForm.tsx]: Ah the reason this fails is because the props are different from the others as you say - this is because I did this form a long time ago before I learnt the better way of doing it I have done for the others, sorry I meant to update them all. So this should be

```ts
export function AddHoldingForm({
  username,
  onHoldingCreated,
  showNotification,
}: AddHoldingFormProps) {
```

Then if you get rid of `props.` from the rest of this file you should be good. This new method is called props destructuring, if you want to learn more about it google that phrase.

File: client/src/holdings/AddHoldingForm.tsx [hunk 7]
```diff
@@ -50,7 +54,7 @@ export function AddHoldingForm(props: AddHoldingFormProps) {
             actions.resetForm();
             props.onHoldingCreated(holding);
           } catch (err) {
-            console.error(err);
+            showNotification(`Add Holding ${Symbol} failed!`, 'error');
```
Comment (willbeaufoy) [inline client/src/holdings/AddHoldingForm.tsx]: Needs to be `Add holding ${values.symbol} failed!'

File: client/src/holdings/HoldingsList.tsx [hunk 8]
```diff
@@ -167,14 +171,21 @@ export function HoldingsList({user, fxRates}: IProps) {
...
   async function refreshPrices() {
-    setIsRefreshing(true);
-    await API.refreshPrices();
-    await fetchHoldings(user);
+    try {
+      setIsRefreshing(true);
+      await API.refreshPrices();
+      await fetchHoldings(user);
+    } catch (err) {
+      showNotification('Refresh Prices failed!', 'error');
```
Comment (willbeaufoy) [inline client/src/holdings/HoldingsList.tsx]: Nit: can we have lowercase p on Prices

File: client/src/holdings/HoldingsList.tsx [hunk 9]
```diff
@@ -167,14 +171,21 @@ export function HoldingsList({user, fxRates}: IProps) {
       setTotalPerformance(getTotalPerformance(holdings));
       setHoldings([...holdings]);
     } catch (err) {
-      console.error(err);
+      showNotification(
+        `Delete transaction ${holdings[holdingIndex].symbol} failed!`,
```
Comment (willbeaufoy) [inline client/src/holdings/HoldingsList.tsx]: Can we use the `isTrade` function to use the currect terminology. 

```ts
const transactionType = isTrade(t) ? 'trade' : 'dividend';
showNotification(
  `Delete ${transactionType} ${holdings[holdingIndex].symbol} failed!`,
  'error'
);
```

Also, as we're not doing this `holdings[holdingIndex].symbol` three times in this function, can you do this first at the top of the function?

`const holding = holdings[holdingIndex];`

Then after that you can just use `holding.symbol` instead of `holdings[holdingIndex].symbol`.

File: client/src/holdings/HoldingsList.tsx [hunk 10]
```diff
@@ -111,7 +112,10 @@ export function HoldingsList({user, fxRates}: IProps) {
       setTotalPerformance(getTotalPerformance(holdings));
       setHoldings([...holdings]);
     } catch (err) {
-      console.error(err);
+      showNotification(
+        `Delete Holding ${holdings[holdingIndex].symbol} failed!`,
```
Comment (willbeaufoy) [inline client/src/holdings/HoldingsList.tsx]: Can we have holding lowercase

**Review by willbeaufoy — CHANGES_REQUESTED** [review]

File: client/src/App.tsx [hunk 11]
```diff
@@ -21,6 +23,11 @@ function App() {
     currency: '',
   });
   const [fxRates, setFxRates] = useState<FxRates>({CAD: 1, EUR: 1, USD: 1});
+  const [isSnackbarOpen, setIsSnackbarOpen] = useState(false);
+  const [snackbarMessage, setSnackbarMessage] = useState('');
+  const [alertColor, setAlertColor] = useState<AlertColor | undefined>(
+    undefined
```
Comment (willbeaufoy) [inline client/src/App.tsx]: I think you can remove this undefined cos having nothing in the brackets is probably treated the same as explicit undefined

File: client/src/holdings/AddDividendDialog.tsx [hunk 12]
```diff
@@ -61,7 +66,10 @@ export function AddDividendDialog({holding, onDividendCreated}: IProps) {
               onDividendCreated(dividend);
               setOpen(false);
             } catch (err) {
-              console.error(err);
+              showNotification(
+                `Create dividend ${holding.symbol} failed!`,
```
Comment (willbeaufoy) [inline client/src/holdings/AddDividendDialog.tsx]: Can you add the word 'for' so it's 'Create dividend for...'

File: .vscode/settings.json [hunk 13]
```diff
@@ -5,4 +5,5 @@
     "importSorter.importStringConfiguration.spacingPerImportExpression.afterStartingBracket": 0,
     "importSorter.importStringConfiguration.spacingPerImportExpression.beforeEndingBracket": 0,
     "typescript.format.enable": false,
+    "prettier.trailingComma": "none",
```
Comment (willbeaufoy) [inline .vscode/settings.json]: Hmm I'd like to get to the bottom of this rather than just turning trailingComma off. When I save AddHoldingForm it just puts the destructured props one on each line? So it's no problem? The trailing comma was only a problem when they were all on one line, sorry if that wasn't clear.

**Review by willbeaufoy — CHANGES_REQUESTED** [review]
